apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-alqi
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0033-tenant/tkrw-pr712-0075-0033-app/devfile-sample-alqi@sha256:de3061ad314e93c6d2bc4901150094cbdb92e7b8f129f1130711e29ce2cbf520
        name: my-nodejs
        resources: {}
status: {}
